# Generated by Django 3.1.4 on 2020-12-05 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DukeLester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=200)),
                ('MiddleName', models.CharField(max_length=200)),
                ('LastName', models.CharField(max_length=200)),
                ('age', models.IntegerField(default=0)),
                ('gender', models.CharField(max_length=45)),
                ('status', models.CharField(max_length=45)),
            ],
        ),
    ]
